Game-as-a-Service/Lobby-Platform-Service

- README.md
> Docs: Add the contributor list.

- AUTHORS
> Increase an author

- .idea/.gitignore
- application/pom.xml
- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/WalkingSkeletonRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/WalkingSkeletonUseCase.kt
- domain/pom.xml
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/WalkingSkeleton.kt
- domain/src/test/kotlin/tw/waterballsa/gaas/domain/WalkingSkeletonTest.kt
- pom.xml
- spring/pom.xml
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/LobbyPlatformApplication.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/WalkingSkeletonController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringWalkingSkeletonRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/WalkingSkeletonDAO.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/WalkingSkeletonData.kt
- spring/src/main/resources/application-dev.yaml
- spring/src/main/resources/application.yaml
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/WalkingSkeletonControllerTest.kt
- So everyone can start develop.
- Whole project
- Whole project
- resolved #19
> :bricks: walking skeleton

- application/pom.xml
- domain/pom.xml
- spring/pom.xml
…unconsistent of kotlin and spring boot 2.7.10
> Fix issue with 'mvn install'

- application/pom.xml
- domain/pom.xml
- pom.xml
- spring/pom.xml
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/resources/application-dev.yaml
- As a user, I want to login by Google account
- SecurityConfig
- OAuth2Controller
- 
- resolved #22
> :sparkles: 實作 Google 第三方登入、修正 groupId

- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/GameRegistrationRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/RegisterGameUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/GameRegistration.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/DomainEvent.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/RegisteredGameEvent.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/advices/GameRegistrationAdvice.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameRegistrationRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/GameRegistrationDAO.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameRegistrationData.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationControllerTest.kt
- As a user, I want to register my game.
- New Feature: GameRegistration
- GameRegistrationController
- resolved #32
> :sparkles: 實作遊戲註冊功能

- application/src/main/kotlin/tw/waterballsa/gaas/application/exceptions/DuplicateRoomException.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/exceptions/GameAlreadyExistsException.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/GameRegistrationRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/RoomRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateRoomUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Player.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/CreatedRoomEvent.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/DomainEvent.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/PlayerNumberCompatibilityException.kt
- domain/src/test/kotlin/tw/waterballsa/gaas/domain/WalkingSkeletonTest.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/advices/GameRegistrationAdvice.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/extensions/OptionalExtensions.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameRegistrationRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/RoomDAO.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/UserDAO.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/RoomData.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationControllerTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/RoomControllerTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/UserControllerTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/model/TestCreatedRoom.kt
- As a user I want to create a room
- Room related
- RoomController
- none
> :sparkles: 實作建立房間

- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/GameRegistrationRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetGameRegistrationsUsecase.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameRegistrationRepository.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationControllerTest.kt
- As a user, I want to view all registered games.
- GameRegistration
- GameRegistration
- resolved #55
> :sparkles: 實作取得遊戲列表

- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/UserRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/UserCreatedEvent.kt
- spring/pom.xml
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/UserDAO.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
- As game lobby, when new user login, then create user
- New Feature: Create new user
- OAuth2Controller
- resolved #24
> 使用第三方登入後，新增使用者

- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/UserRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/UserCreatedEvent.kt
- spring/pom.xml
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomOAuthorizationRequestResolver.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/IdentityProvider.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/utils/WebClientUtils.kt
- spring/src/main/resources/application-dev.yaml
- spring/src/main/resources/application.yaml
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/WalkingSkeletonControllerTest.kt
- 需要一個固定的 Endpoint 來處理登入。
- spring module
- none
- resolved #67
> :sparkles: 新增具體第三方登入 Endpoint

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/IdTokenAuthenticationFilter.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
- As a user, I need to login to access the system.
- Security Config add IdTokenAuthenticationFilter
- none
- resolved #69
> 新增 Filter 處理 JWT (Id Token)

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/OpenApiConfig.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
- spring/src/main/resources/application-dev.yaml
- spring/src/main/resources/application.yaml
- open swagger-ui to everyone
- security and application.yml
- open swagger-ui
- resolved #68
> feat : 新增swagger-ui 開放給所有人看

- application/src/main/kotlin/tw/waterballsa/gaas/application/extension/UserExtensions.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/model/Pagination.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
- pom.xml
- pre-commit
- 將 ktlint 加入 git hook，在 pre-commit 階段自動執行。
- pom.xml
- none
- none
> :hammer: 調整 ktlint 和新增 git hook

- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/ChangePlayerReadinessUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameRegistrationRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameRegistrationData.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/RoomData.kt
- 改用 @DBRef 註解搜尋關聯，省去手動 Query 的麻煩。
- RoomData
- none
- none
> :recycle: 改用 @DBRef 註解搜尋關聯

- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/HostKickPlayerUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/KickPlayerUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- As a host, need to kick other player out of room
- room related
- RoomController
- #98
> feat : KickPlayerUseCase 開發完畢

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- replace Oidc with JWT
-
-
- resolve https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/114
> RoomController replace Oidc with JWT

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/resources/application-dev.yaml
- spring/src/main/resources/application.yaml
- When my access token expires, I need to renew it.
- Add refresh access token api.
- OAuth2 scope: add offline_access to get a refresh token.
- none
- resolves https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/113
> feature: refresh access token api

- application/src/main/kotlin/tw/waterballsa/gaas/application/exceptions/GameAlreadyExistsException.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/AbstractRoomUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateRoomUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/RegisterGameUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/PlatformException.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/enums/PlatformError.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/aspects/PlatformExceptionHandler.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/viewmodel/PlatformViewModel.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
- the PlatformViewModel need to have a spec 
- Refactor PlatformException and Exception Handler
- Exception Message need have a title and message
- resolve #119
> 回傳前端Exception Message格式化

- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateRoomUsecase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
-Readiness oriented room host
-Room related
-RoomController
-#118
> 實作房主IsReady always True

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/models/TestGetRoomsRequest.kt
- front end parameter name want change to perPage
- parameter name offset -> perPage
- none
- resolve #138
> :refactor frontend need change parameter name offset to perPage

- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- #156   url wrong
- fix url 
- none
-  #169
> fix startGame url

- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/RoomDAO.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- host can join room again
- fix this bug
- room controller test
- #163
> :fix host can join room again

- README-en.md
- As titled
-
-
- https://github.com/Game-as-a-Service/Lobby-Platform-Service/discussions/97
> docs: add English version README

- .github/workflows/build-and-deploy.yml
CI/CD failed with multiline commit message
- .github\workflows\build-and-deploy.yml
- resolve #179
> :bug: fix: ci-cd multiline echo

- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/StartGameUseCase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/StartedGameEvent.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/events/enums/EventMessageType.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/enums/SocketIOEventMessage.kt
- need to boardcast StartGameEvent
- create a startGameEvent
- none
- #176
> feat start game event broadcast

- domain/src/main/kotlin/tw/waterballsa/gaas/events/SocketioEvent.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/ServerCommandLineRunner.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventName.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOProperties.kt
- create room, join room and leave room for websocket
- add two event
-  socket io can only use postman to test event
- resolve #168 
- resolve #151
> update join room, create room and leave room

- .github/workflows/build-and-deploy.yml
- zbpack.json
- GitHub Actions error
https://github.com/Game-as-a-Service/Lobby-Platform-Service/actions/runs/13217509579
- add Zeabur & upgrade download-artifact@v4
> 👷 DevOps: add Zeabur & upgrade download-artifact@v4

- .github/workflows/build-and-deploy.yml
- we moved to Zeabur
- remove AWS deployment
> refactor: remove AWS deployment

- application/src/main/kotlin/tw/waterballsa/gaas/application/client/GameService.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/StartGameUseCase.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
- resolve #231 
- game player add nickname field.
- RoomController
- #231
> fix: game player add nickname field

- application/src/main/kotlin/tw/waterballsa/gaas/application/presenters/GameRegistrationPresenter.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/GameCollectionRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/GameRegistrationRepository.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/AbstractGameCollectionUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CollectGameUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetGameCollectionsUseCase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetGameRegistrationsUsecase.kt
- application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UnCollectGameUseCase.kt
- domain/src/main/kotlin/tw/waterballsa/gaas/domain/GameCollection.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/GameCollectionController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/GameRegistrationController.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/presenter/RenderGameRegistrationPresenter.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/viewmodel/GameRegistrationViewModel.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameCollectionRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringGameRegistrationRepository.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/GameCollectionDAO.kt
- spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameCollectionData.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/GameCollectionControllerTest.kt
- spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/GameRegistrationControllerTest.kt
- resolve #211
- Add apis for managing game collections.
- GameCollectionControllerTest.kt
- #211
> feature: collect game
